target_catastrophizing = [
   "will fail",
"gonna fail",
"will go wrong",
"will end",
"will be impossible",
"will b impossible",
"will not happen",
"won't happen",
"ain't gonna happen",
"not gonna happen",
"will be terrible",
"will b terrible",
"gonna be terrible",
"gonna b terrible",
"will be horrible",
"will b horrible",
"gonna be horrible",
"gonna b horrible",
"will be a catastrophe",
"will b a catastrophe",
"gonna be a catastrophe",
"gonna b a catastrophe",
"will be catastrophe",
"will b catastrophe",
"gonna be catastrophe",
"gonna b catastrophe",
"will be a disaster",
"will b a disaster",
"gonna be a disaster",
"gonna b a disaster",
"will be disaster",
"will b disaster",
"gonna be disaster",
"gonna b disaster",
"will never end",
"will nvr end",
"won't end",
"never gonna end",
"never gonna nd",
"will not end",
"won't end"
]
target_dichotomous_Reasoning = [
"only",
"every",
"everyone",
"every1",
"everybody",
"evrybdy",
"everything",
"everywhere",
"always",
"alwayz",
"perfect",
"prfct",
"the best",
"da best",
"all",
"not a single",
"no one",
"no1",
"noone",
"nobody",
"nobdy",
"nothing",
"nothin",
"nowhere",
"never",
"nvr",
"worthless",
"the worst",
"da worst",
"neither",
"nor",
"either or",
"either/or",
"black or white",
"ever"
]
target_disqualifying_the_positives = ["great but",
"grt but",
"gr8 but",
"good but",
"OK but",
"okay but",
"not that great",
"not that gr8",
"not that good",
"it was not",
"it wasnt",
"it wasn't",
"not all that",
"fine but",
"F9 but",
"acceptable but",
"xceptable but",
"great yet",
"gr8 yet",
"good yet",
"OK yet",
"okay yet",
"fine yet",
"f9 yet",
"acceptable yet",
"xceptable yet"]
target_emotional_reasoning = [
"but I feel",
"since I feel",
"because I feel",
"becoz I feel",
"bcz I feel",
"coz I feel",
"cuz I feel",
"but it feels",
"since it feels",
"snce it feels",
"because it feels",
"becoz it feels",
"bcz it feels",
"coz it feels",
"cuz it feels",
"still feelsl",
"stil feels"
]
target_fortune_telling = [
"I will not",
"I won't",
"I'll not",
"we will not",
"we won't",
"we'll not",
"you will not",
"you won't",
"you'll not",
"they will not",
"they won't",
"they'll not",
"it will not",
"it won't",
"it'll not",
"that will not",
"that won't",
"that'll not",
"he will not",
"he won't",
"he'll not",
"she will not",
"she won't",
"she'll not"
]
target_labeling_and_mislabeling = [
"I am a",
"I'm a",
"Im a",
"Imma",
"he is a",
"he's a",
"she is a",
"she's a",
"they are a",
"theyre a",
"they're a",
"it is a",
"its a",
"it's a",
"that is a",
"thats a",
"that's a",
"sucks at",
"sux at",
"sucks @",
"sux @",
"suck at",
"suck @",
"I never",
"I nevr",
"I neva",
"he never",
"he nevr",
"he neva",
"she never",
"she nevr",
"she neva",
"you never",
"you nvr",
"you nevr",
"you neva",
"u never",
"u nvr",
"u nevr",
"u neva",
"we never",
"we nvr",
"we nevr",
"v neva",
"v never",
"v nvr",
"v nevr",
"v neva",
"they never",
"they nevr",
"they neva",
"I am an",
"Im an",
"I'm an",
"he is an",
"he's an",
"she is an",
"she's an",
"they are an",
"theyre an",
"they're an",
"it is an",
"its an",
"it's an",
"that is an",
"thats an",
"that's an",
"a burden",
"a complete",
"a complte",
"a completely",
"a huge",
"a loser",
"a major",
"a total",
"a totally",
"a weak",
"an absolute",
"an utter",
"a bad",
"a broken",
"a brokn",
"a damaged",
"a damagd",
"a helpless",
"a hopeless",
"an incompetent",
"a toxic",
"an ugly",
"an undesirable",
"an unlovable",
"a worthless",
"a horrible",
"a terrible"
]
target_magnification_and_minimization = [
"worst",
"wrst",
"best",
"bst",
"not important",
"nt important",
"not imprtnt",
"not imp",
"not count",
"nt count",
"not matter",
"nt matter",
"not mattr",
"no matter",
"no mattr",
"the only thing",
"the only thng",
"the one thing",
"the 1 thing",
"the one thng"
]
target_mental_filtering = [
"I see only",
"I c only",
"I see only",
"all I see",
"all I c",
"all I seee",
"all I can see",
"all I can c",
"all I can seee",
"can only think",
"can only thnk",
"nothing good",
"nthng good",
"nothng good",
"nothing right",
"nthng right",
"nthing right",
"nothng right",
"completely bad",
"completely wrong",
"completely wrng",
"only the bad",
"only the worst",
"only the wrst",
"if I just",
"if I justt",
"if I only",
"if it just",
"if it justt",
"if it only"
]
target_mindreading = [
"everyone believes",
"every1 believes",
"everyone knows",
"every1 knows",
"everyone thinks",
"every1 thinks",
"everyone will believe",
"everyone'll believe",
"every1 will believe",
"everyone will know",
"everyone'll know",
"every1 will know",
"everyone will think",
"everyone'll think",
"every1 will think",
"nobody believes",
"nobdy believes",
"nobody knows",
"nobdy knows",
"nobody thinks",
"nobdy thinks",
"nobody will believe",
"nobdy will believe",
"nobody'll believe",
"nobody will know",
"nobdy will know",
"nobody'll know",
"nobody will think",
"nobdy will think",
"nobody'll think",
"he believes",
"he knows",
"he thinks",
"he does not believe",
"he doesn't believe",
"he doesnt believe",
"he does not know",
"he doesn't know",
"he doesnt know",
"he does not think",
"he doesn't think",
"he doesnt think",
"he will believe",
"he'll believe",
"he will know",
"he'll know",
"he will think",
"he'll think",
"he will not believe",
"he won't believe",
"he wont believe",
"he'll not believe"
"he will not know",
"he won't know",
"he wont know",
"he'll not know",
"he will not think",
"he won't think",
"he wont think",
"he'll not think",
"she believes",
"she knows",
"she thinks",
"she does not believe",
"she doesn't believe",
"she doesnt believe",
"she does not know",
"she doesn't know",
"she doesnt know",
"she does not think",
"she doesn't think",
"she doesnt think",
"she will believe",
"she'll believe",
"she will know",
"she'll know",
"she will think",
"she'll think",
"she will not believe",
"she'll not believe"
"she won't believe",
"she wont believe",
"she will not know",
"she'll not know",
"she won't know",
"she wont know",
"she will not think",
"she'll not think",
"she won't think",
"she wont think",
"they believes",
"they knows",
"they thinks",
"they do not believe",
"they don't believe",
"they dont believe",
"they do not know",
"they don't know",
"they dont know",
"they do not think",
"they don't think",
"they dont think",
"they will believe",
"they'll believe",
"they will know",
"they'll know",
"they will think",
"they'll think",
"they will not believe",
"they'll not believe",
"they won't believe",
"they wont believe",
"they will not know",
"they'll not know",
"they won't know",
"they wont know",
"they will not think",
"they won't think",
"they wont think",
"they'll not think",
"we believe",
"we knows",
"we thinks",
"we do not believe",
"we don't believe",
"we dont believe",
"we do not know",
"we don't know",
"we dont know",
"we do not think",
"we don't think",
"we dont think",
"we will believe",
"we'll believe",
"we will know",
"we'll know",
"we will think",
"we'll think",
"we will not believe",
"we'll not believe",
"we won't believe",
"we wont believe",
"we will not know",
"we' wi'll not know",
"we won't know",
"we wont know",
"we will not think",
"we'll not think",
"we won't think",
"we wont think",
"you believe",
"u believe",
"you knows",
"u knows",
"you thinks",
"u thinks",
"you do not believe",
"you don't believe",
"you dont believe",
"u do not believe",
"u don't believe",
"u dont believe",
"you do not know",
"you don't know",
"you dont know",
"u do not know",
"u don't know",
"u dont know",
"you do not think",
"you don't think",
"you dont think",
"u do not think",
"u don't think",
"u dont think",
"you will believe",
"you'll believe",
"u will believe",
"u'll believe",
"you will know",
"you'll know",
"u will know",
"u'll know",
"you will think",
"you'll think",
"u will think",
"u'll think",
"you will not believe",
"you won't believe",
"you wont believe",
"you'll not believe",
"u will not believe",
"u won't believe",
"u wont believe",
"u'll not believe",
"you will not know",
"you won't know",
"you wont know",
"you'll not know",
"u'll not know",
"u will not know",
"u won't know",
"u wont know",
"you will not think",
"you won't think",
"you wont think",
"you'll not think",
"u'll not think",
"u will not think",
"u won't think",
"u wont think"
]
target_overgeneralizing = [
"all of the time",
"all of them",
"all of em",
"all the time",
"always happens",
"alwayz happens",
"always like",
"alwayz like",
"happens every time",
"happens evry time",
"completely",
"no one ever",
"no1 ever",
"no1 evr",
"no one evr",
"nobody ever",
"nobdy ever",
"nobdy evr",
"nobody evr",
"every single one of them",
"every single 1 of them",
"every single one of you",
"every single 1 of you",
"I always",
"I alwayz",
"you always",
"you alwayz",
"he always",
"he alwayz",
"she always",
"she alwayz",
"they always",
"they alwayz",
"I am always",
"I'm always",
"I am alwayz",
"I alwayz",
"you are always",
"you're always",
"you're alwayz",
"you are alwayz",
"he is always",
"he is alwayz",
"he's always",
"he's alwayz",
"she is always",
"she is alwayz",
"she's always",
"she's alwayz",
"they are always",
"they are alwayz",
"they're always",
"they're alwayz"
]
target_personalizing = [
"all me",
"all my",
"because I",
"becoz I",
"bcz I",
"coz I",
"cuz I",
"because my",
"becoz my",
"bcz my",
"coz my",
"cuz my",
"because of my",
"becoz of my",
"bcz of my",
"coz of my",
"cuz of my",
"because of me",
"becoz of me",
"bcz of me",
"coz of me",
"cuz of me",
"I am responsible",
"Im responsible",
"I'm responsible",
"blame me",
"I caused",
"I cauzed",
"I feel responsible",
"all my doing",
"all my doin",
"all my fault",
"my bad",
"my responsibility"
]
target_should_statements = [
"should",
"ought",
"must",
"have to",
"hav to",
"has to"
]